### ISSUE TITLE
Only Writes Headings in CSV File

### ISSUE THREAD

**Issue by mani1soni** [shreyas707/Amazon-Review-Scraper#1]
when i run the code, it makes a CSV file and only writes headings of csv file not reviews..
how i get reviews

**Comment by oguzhari** [comment]
Same issues. But When I use another country, like chine or brazil or germany its return all of reviews. Only same issues with amazon us

**Comment by mani1soni** [comment]
Okay, i will try with another country

**Comment by amnghd** [comment]
I used UK. Still not wrking.

**Comment by vijaybendigeri** [comment]
Having the same issues. Only copies header and no content. I tried US and India.

**Comment by oguzhari** [comment]
I just partially solve problem. just US doesnt work. Except all work finely

**Comment by vijaybendigeri** [comment]
I tried using it for India and getting the same problem.

**Comment by pratikchhapolika** [comment]
Not working for India also. :(

**Comment by shreyas707** [comment]
Guys, sorry but this is an old project of mine. Amazon can change a single div element and the script won't work

I don't have the time to maintain this project anymore, but if you can fix it and raise a PR, I'll gladly merge it :)
