### ISSUE TITLE
It always says wrong url.

### ISSUE THREAD

**Issue by danielp3011** [shreyas707/Amazon-Review-Scraper#3]
I tried a lot of different variants but I couldn't make it work. Does anybody has an idea what to do?

**Comment by antondoberschuetz** [comment]
same here I tried:
- product page
- product review page
- product review page + pageNumber

**Comment by shreyas707** [comment]
Guys, sorry but this is an old project of mine. Amazon can change a single div element and the script won't work

I don't have the time to maintain this project anymore, but if you can fix it and raise a PR, I'll gladly merge it :)
